// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.11
// source: office.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OfficeService_CreatOffice_FullMethodName  = "/pb.officeService/CreatOffice"
	OfficeService_DeleteOffice_FullMethodName = "/pb.officeService/DeleteOffice"
	OfficeService_UpdateOffice_FullMethodName = "/pb.officeService/UpdateOffice"
	OfficeService_GetOffice_FullMethodName    = "/pb.officeService/GetOffice"
	OfficeService_ListOffice_FullMethodName   = "/pb.officeService/ListOffice"
)

// OfficeServiceClient is the client API for OfficeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OfficeServiceClient interface {
	CreatOffice(ctx context.Context, in *CreateOfficeRequest, opts ...grpc.CallOption) (*CreateOfficeResponse, error)
	DeleteOffice(ctx context.Context, in *DeleteOfficeRequest, opts ...grpc.CallOption) (*DeleteOfficeResponse, error)
	UpdateOffice(ctx context.Context, in *UpdateOfficeRequest, opts ...grpc.CallOption) (*UpdateOfficeResponse, error)
	GetOffice(ctx context.Context, in *GetOfficeRequest, opts ...grpc.CallOption) (*GetOfficeResponse, error)
	ListOffice(ctx context.Context, in *ListOfficeRequest, opts ...grpc.CallOption) (*ListOfficeResponse, error)
}

type officeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOfficeServiceClient(cc grpc.ClientConnInterface) OfficeServiceClient {
	return &officeServiceClient{cc}
}

func (c *officeServiceClient) CreatOffice(ctx context.Context, in *CreateOfficeRequest, opts ...grpc.CallOption) (*CreateOfficeResponse, error) {
	out := new(CreateOfficeResponse)
	err := c.cc.Invoke(ctx, OfficeService_CreatOffice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeServiceClient) DeleteOffice(ctx context.Context, in *DeleteOfficeRequest, opts ...grpc.CallOption) (*DeleteOfficeResponse, error) {
	out := new(DeleteOfficeResponse)
	err := c.cc.Invoke(ctx, OfficeService_DeleteOffice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeServiceClient) UpdateOffice(ctx context.Context, in *UpdateOfficeRequest, opts ...grpc.CallOption) (*UpdateOfficeResponse, error) {
	out := new(UpdateOfficeResponse)
	err := c.cc.Invoke(ctx, OfficeService_UpdateOffice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeServiceClient) GetOffice(ctx context.Context, in *GetOfficeRequest, opts ...grpc.CallOption) (*GetOfficeResponse, error) {
	out := new(GetOfficeResponse)
	err := c.cc.Invoke(ctx, OfficeService_GetOffice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *officeServiceClient) ListOffice(ctx context.Context, in *ListOfficeRequest, opts ...grpc.CallOption) (*ListOfficeResponse, error) {
	out := new(ListOfficeResponse)
	err := c.cc.Invoke(ctx, OfficeService_ListOffice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfficeServiceServer is the server API for OfficeService service.
// All implementations must embed UnimplementedOfficeServiceServer
// for forward compatibility
type OfficeServiceServer interface {
	CreatOffice(context.Context, *CreateOfficeRequest) (*CreateOfficeResponse, error)
	DeleteOffice(context.Context, *DeleteOfficeRequest) (*DeleteOfficeResponse, error)
	UpdateOffice(context.Context, *UpdateOfficeRequest) (*UpdateOfficeResponse, error)
	GetOffice(context.Context, *GetOfficeRequest) (*GetOfficeResponse, error)
	ListOffice(context.Context, *ListOfficeRequest) (*ListOfficeResponse, error)
	mustEmbedUnimplementedOfficeServiceServer()
}

// UnimplementedOfficeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOfficeServiceServer struct {
}

func (UnimplementedOfficeServiceServer) CreatOffice(context.Context, *CreateOfficeRequest) (*CreateOfficeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatOffice not implemented")
}
func (UnimplementedOfficeServiceServer) DeleteOffice(context.Context, *DeleteOfficeRequest) (*DeleteOfficeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOffice not implemented")
}
func (UnimplementedOfficeServiceServer) UpdateOffice(context.Context, *UpdateOfficeRequest) (*UpdateOfficeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOffice not implemented")
}
func (UnimplementedOfficeServiceServer) GetOffice(context.Context, *GetOfficeRequest) (*GetOfficeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOffice not implemented")
}
func (UnimplementedOfficeServiceServer) ListOffice(context.Context, *ListOfficeRequest) (*ListOfficeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOffice not implemented")
}
func (UnimplementedOfficeServiceServer) mustEmbedUnimplementedOfficeServiceServer() {}

// UnsafeOfficeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfficeServiceServer will
// result in compilation errors.
type UnsafeOfficeServiceServer interface {
	mustEmbedUnimplementedOfficeServiceServer()
}

func RegisterOfficeServiceServer(s grpc.ServiceRegistrar, srv OfficeServiceServer) {
	s.RegisterService(&OfficeService_ServiceDesc, srv)
}

func _OfficeService_CreatOffice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOfficeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServiceServer).CreatOffice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfficeService_CreatOffice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServiceServer).CreatOffice(ctx, req.(*CreateOfficeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfficeService_DeleteOffice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOfficeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServiceServer).DeleteOffice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfficeService_DeleteOffice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServiceServer).DeleteOffice(ctx, req.(*DeleteOfficeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfficeService_UpdateOffice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOfficeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServiceServer).UpdateOffice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfficeService_UpdateOffice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServiceServer).UpdateOffice(ctx, req.(*UpdateOfficeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfficeService_GetOffice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOfficeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServiceServer).GetOffice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfficeService_GetOffice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServiceServer).GetOffice(ctx, req.(*GetOfficeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfficeService_ListOffice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOfficeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfficeServiceServer).ListOffice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfficeService_ListOffice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfficeServiceServer).ListOffice(ctx, req.(*ListOfficeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OfficeService_ServiceDesc is the grpc.ServiceDesc for OfficeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OfficeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.officeService",
	HandlerType: (*OfficeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatOffice",
			Handler:    _OfficeService_CreatOffice_Handler,
		},
		{
			MethodName: "DeleteOffice",
			Handler:    _OfficeService_DeleteOffice_Handler,
		},
		{
			MethodName: "UpdateOffice",
			Handler:    _OfficeService_UpdateOffice_Handler,
		},
		{
			MethodName: "GetOffice",
			Handler:    _OfficeService_GetOffice_Handler,
		},
		{
			MethodName: "ListOffice",
			Handler:    _OfficeService_ListOffice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "office.proto",
}
