// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.11
// source: office.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 办公室结构体
type Office struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          //办公室编号
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       //办公室名称
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` //办公室地址
}

func (x *Office) Reset() {
	*x = Office{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Office) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Office) ProtoMessage() {}

func (x *Office) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Office.ProtoReflect.Descriptor instead.
func (*Office) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{0}
}

func (x *Office) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Office) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Office) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// 创建办公室
type CreateOfficeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       //办公室名称
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"` //办公室地址
}

func (x *CreateOfficeRequest) Reset() {
	*x = CreateOfficeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOfficeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfficeRequest) ProtoMessage() {}

func (x *CreateOfficeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfficeRequest.ProtoReflect.Descriptor instead.
func (*CreateOfficeRequest) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOfficeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOfficeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateOfficeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` //是否创建成功
}

func (x *CreateOfficeResponse) Reset() {
	*x = CreateOfficeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOfficeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfficeResponse) ProtoMessage() {}

func (x *CreateOfficeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfficeResponse.ProtoReflect.Descriptor instead.
func (*CreateOfficeResponse) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOfficeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 删除办公室
type DeleteOfficeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //办公室id
}

func (x *DeleteOfficeRequest) Reset() {
	*x = DeleteOfficeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOfficeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOfficeRequest) ProtoMessage() {}

func (x *DeleteOfficeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOfficeRequest.ProtoReflect.Descriptor instead.
func (*DeleteOfficeRequest) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteOfficeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteOfficeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` //是否删除成功
}

func (x *DeleteOfficeResponse) Reset() {
	*x = DeleteOfficeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOfficeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOfficeResponse) ProtoMessage() {}

func (x *DeleteOfficeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOfficeResponse.ProtoReflect.Descriptor instead.
func (*DeleteOfficeResponse) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteOfficeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 更新办公室
type UpdateOfficeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          //办公室编号
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       //办公室名称
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` //办公室地址
}

func (x *UpdateOfficeRequest) Reset() {
	*x = UpdateOfficeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOfficeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfficeRequest) ProtoMessage() {}

func (x *UpdateOfficeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfficeRequest.ProtoReflect.Descriptor instead.
func (*UpdateOfficeRequest) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOfficeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOfficeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOfficeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type UpdateOfficeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"` //是否更新成功
}

func (x *UpdateOfficeResponse) Reset() {
	*x = UpdateOfficeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOfficeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfficeResponse) ProtoMessage() {}

func (x *UpdateOfficeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfficeResponse.ProtoReflect.Descriptor instead.
func (*UpdateOfficeResponse) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOfficeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 查询办公室
type GetOfficeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //办公室id
}

func (x *GetOfficeRequest) Reset() {
	*x = GetOfficeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOfficeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfficeRequest) ProtoMessage() {}

func (x *GetOfficeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfficeRequest.ProtoReflect.Descriptor instead.
func (*GetOfficeRequest) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{7}
}

func (x *GetOfficeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetOfficeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Office *Office `protobuf:"bytes,1,opt,name=office,proto3" json:"office,omitempty"` //办公室信息
}

func (x *GetOfficeResponse) Reset() {
	*x = GetOfficeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOfficeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfficeResponse) ProtoMessage() {}

func (x *GetOfficeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfficeResponse.ProtoReflect.Descriptor instead.
func (*GetOfficeResponse) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{8}
}

func (x *GetOfficeResponse) GetOffice() *Office {
	if x != nil {
		return x.Office
	}
	return nil
}

// 查询办公室列表
type ListOfficeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`         //页码
	PageSize int64  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"` //每页数量
	Search   string `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`      //搜索关键字
	Order    string `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`        //排序字段
	Sort     string `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`          //排序方式,desc or as
}

func (x *ListOfficeRequest) Reset() {
	*x = ListOfficeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfficeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfficeRequest) ProtoMessage() {}

func (x *ListOfficeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfficeRequest.ProtoReflect.Descriptor instead.
func (*ListOfficeRequest) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{9}
}

func (x *ListOfficeRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOfficeRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOfficeRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListOfficeRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *ListOfficeRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

type ListOfficeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` //总数
	List  []*Office `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`    //办公室列表
}

func (x *ListOfficeResponse) Reset() {
	*x = ListOfficeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_office_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfficeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfficeResponse) ProtoMessage() {}

func (x *ListOfficeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_office_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfficeResponse.ProtoReflect.Descriptor instead.
func (*ListOfficeResponse) Descriptor() ([]byte, []int) {
	return file_office_proto_rawDescGZIP(), []int{10}
}

func (x *ListOfficeResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOfficeResponse) GetList() []*Office {
	if x != nil {
		return x.List
	}
	return nil
}

var File_office_proto protoreflect.FileDescriptor

var file_office_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x46, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x43, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x28, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x28, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x53, 0x0a, 0x13, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x28, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x22, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f,
	0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x22, 0x4a,
	0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x66,
	0x66, 0x69, 0x63, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xce, 0x02, 0x0a, 0x0d, 0x6f,
	0x66, 0x66, 0x69, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x0b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x62,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x12, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x41, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63,
	0x65, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63,
	0x65, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_office_proto_rawDescOnce sync.Once
	file_office_proto_rawDescData = file_office_proto_rawDesc
)

func file_office_proto_rawDescGZIP() []byte {
	file_office_proto_rawDescOnce.Do(func() {
		file_office_proto_rawDescData = protoimpl.X.CompressGZIP(file_office_proto_rawDescData)
	})
	return file_office_proto_rawDescData
}

var file_office_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_office_proto_goTypes = []interface{}{
	(*Office)(nil),               // 0: pb.Office
	(*CreateOfficeRequest)(nil),  // 1: pb.CreateOfficeRequest
	(*CreateOfficeResponse)(nil), // 2: pb.CreateOfficeResponse
	(*DeleteOfficeRequest)(nil),  // 3: pb.DeleteOfficeRequest
	(*DeleteOfficeResponse)(nil), // 4: pb.DeleteOfficeResponse
	(*UpdateOfficeRequest)(nil),  // 5: pb.UpdateOfficeRequest
	(*UpdateOfficeResponse)(nil), // 6: pb.UpdateOfficeResponse
	(*GetOfficeRequest)(nil),     // 7: pb.GetOfficeRequest
	(*GetOfficeResponse)(nil),    // 8: pb.GetOfficeResponse
	(*ListOfficeRequest)(nil),    // 9: pb.ListOfficeRequest
	(*ListOfficeResponse)(nil),   // 10: pb.ListOfficeResponse
}
var file_office_proto_depIdxs = []int32{
	0,  // 0: pb.GetOfficeResponse.office:type_name -> pb.Office
	0,  // 1: pb.ListOfficeResponse.list:type_name -> pb.Office
	1,  // 2: pb.officeService.CreatOffice:input_type -> pb.CreateOfficeRequest
	3,  // 3: pb.officeService.DeleteOffice:input_type -> pb.DeleteOfficeRequest
	5,  // 4: pb.officeService.UpdateOffice:input_type -> pb.UpdateOfficeRequest
	7,  // 5: pb.officeService.GetOffice:input_type -> pb.GetOfficeRequest
	9,  // 6: pb.officeService.ListOffice:input_type -> pb.ListOfficeRequest
	2,  // 7: pb.officeService.CreatOffice:output_type -> pb.CreateOfficeResponse
	4,  // 8: pb.officeService.DeleteOffice:output_type -> pb.DeleteOfficeResponse
	6,  // 9: pb.officeService.UpdateOffice:output_type -> pb.UpdateOfficeResponse
	8,  // 10: pb.officeService.GetOffice:output_type -> pb.GetOfficeResponse
	10, // 11: pb.officeService.ListOffice:output_type -> pb.ListOfficeResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_office_proto_init() }
func file_office_proto_init() {
	if File_office_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_office_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Office); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOfficeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOfficeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOfficeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOfficeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOfficeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOfficeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOfficeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOfficeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfficeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_office_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfficeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_office_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_office_proto_goTypes,
		DependencyIndexes: file_office_proto_depIdxs,
		MessageInfos:      file_office_proto_msgTypes,
	}.Build()
	File_office_proto = out.File
	file_office_proto_rawDesc = nil
	file_office_proto_goTypes = nil
	file_office_proto_depIdxs = nil
}
