// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.11
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserService_Login_FullMethodName          = "/user.UserService/Login"
	UserService_UserInfo_FullMethodName       = "/user.UserService/UserInfo"
	UserService_UserInfoUpdate_FullMethodName = "/user.UserService/UserInfoUpdate"
	UserService_UserList_FullMethodName       = "/user.UserService/UserList"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error)
	UserInfoUpdate(ctx context.Context, in *UserInfoUpdateReq, opts ...grpc.CallOption) (*UserInfoUpdateResp, error)
	UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	out := new(LoginResp)
	err := c.cc.Invoke(ctx, UserService_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserInfo(ctx context.Context, in *UserInfoReq, opts ...grpc.CallOption) (*UserInfoResp, error) {
	out := new(UserInfoResp)
	err := c.cc.Invoke(ctx, UserService_UserInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserInfoUpdate(ctx context.Context, in *UserInfoUpdateReq, opts ...grpc.CallOption) (*UserInfoUpdateResp, error) {
	out := new(UserInfoUpdateResp)
	err := c.cc.Invoke(ctx, UserService_UserInfoUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserList(ctx context.Context, in *UserListReq, opts ...grpc.CallOption) (*UserListResp, error) {
	out := new(UserListResp)
	err := c.cc.Invoke(ctx, UserService_UserList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	Login(context.Context, *LoginReq) (*LoginResp, error)
	UserInfo(context.Context, *UserInfoReq) (*UserInfoResp, error)
	UserInfoUpdate(context.Context, *UserInfoUpdateReq) (*UserInfoUpdateResp, error)
	UserList(context.Context, *UserListReq) (*UserListResp, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) Login(context.Context, *LoginReq) (*LoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServiceServer) UserInfo(context.Context, *UserInfoReq) (*UserInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfo not implemented")
}
func (UnimplementedUserServiceServer) UserInfoUpdate(context.Context, *UserInfoUpdateReq) (*UserInfoUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInfoUpdate not implemented")
}
func (UnimplementedUserServiceServer) UserList(context.Context, *UserListReq) (*UserListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserList not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserInfo(ctx, req.(*UserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserInfoUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserInfoUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UserInfoUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserInfoUpdate(ctx, req.(*UserInfoUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserList(ctx, req.(*UserListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "UserInfo",
			Handler:    _UserService_UserInfo_Handler,
		},
		{
			MethodName: "UserInfoUpdate",
			Handler:    _UserService_UserInfoUpdate_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _UserService_UserList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

const (
	UserRoleService_UserRoleList_FullMethodName   = "/user.UserRoleService/UserRoleList"
	UserRoleService_UserRoleUpdate_FullMethodName = "/user.UserRoleService/UserRoleUpdate"
	UserRoleService_UserRoleInfo_FullMethodName   = "/user.UserRoleService/UserRoleInfo"
	UserRoleService_UserRoleAdd_FullMethodName    = "/user.UserRoleService/UserRoleAdd"
	UserRoleService_UserRoleDelete_FullMethodName = "/user.UserRoleService/UserRoleDelete"
)

// UserRoleServiceClient is the client API for UserRoleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRoleServiceClient interface {
	UserRoleList(ctx context.Context, in *UserRoleListReq, opts ...grpc.CallOption) (*UserRoleListResp, error)
	UserRoleUpdate(ctx context.Context, in *UserRoleUpdateReq, opts ...grpc.CallOption) (*UserRoleUpdateResp, error)
	UserRoleInfo(ctx context.Context, in *UserRoleInfoReq, opts ...grpc.CallOption) (*UserRoleInfoResp, error)
	UserRoleAdd(ctx context.Context, in *UserRoleAddReq, opts ...grpc.CallOption) (*UserRoleAddResp, error)
	UserRoleDelete(ctx context.Context, in *UserRoleDeleteReq, opts ...grpc.CallOption) (*UserRoleDeleteResp, error)
}

type userRoleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRoleServiceClient(cc grpc.ClientConnInterface) UserRoleServiceClient {
	return &userRoleServiceClient{cc}
}

func (c *userRoleServiceClient) UserRoleList(ctx context.Context, in *UserRoleListReq, opts ...grpc.CallOption) (*UserRoleListResp, error) {
	out := new(UserRoleListResp)
	err := c.cc.Invoke(ctx, UserRoleService_UserRoleList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleServiceClient) UserRoleUpdate(ctx context.Context, in *UserRoleUpdateReq, opts ...grpc.CallOption) (*UserRoleUpdateResp, error) {
	out := new(UserRoleUpdateResp)
	err := c.cc.Invoke(ctx, UserRoleService_UserRoleUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleServiceClient) UserRoleInfo(ctx context.Context, in *UserRoleInfoReq, opts ...grpc.CallOption) (*UserRoleInfoResp, error) {
	out := new(UserRoleInfoResp)
	err := c.cc.Invoke(ctx, UserRoleService_UserRoleInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleServiceClient) UserRoleAdd(ctx context.Context, in *UserRoleAddReq, opts ...grpc.CallOption) (*UserRoleAddResp, error) {
	out := new(UserRoleAddResp)
	err := c.cc.Invoke(ctx, UserRoleService_UserRoleAdd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userRoleServiceClient) UserRoleDelete(ctx context.Context, in *UserRoleDeleteReq, opts ...grpc.CallOption) (*UserRoleDeleteResp, error) {
	out := new(UserRoleDeleteResp)
	err := c.cc.Invoke(ctx, UserRoleService_UserRoleDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRoleServiceServer is the server API for UserRoleService service.
// All implementations must embed UnimplementedUserRoleServiceServer
// for forward compatibility
type UserRoleServiceServer interface {
	UserRoleList(context.Context, *UserRoleListReq) (*UserRoleListResp, error)
	UserRoleUpdate(context.Context, *UserRoleUpdateReq) (*UserRoleUpdateResp, error)
	UserRoleInfo(context.Context, *UserRoleInfoReq) (*UserRoleInfoResp, error)
	UserRoleAdd(context.Context, *UserRoleAddReq) (*UserRoleAddResp, error)
	UserRoleDelete(context.Context, *UserRoleDeleteReq) (*UserRoleDeleteResp, error)
	mustEmbedUnimplementedUserRoleServiceServer()
}

// UnimplementedUserRoleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserRoleServiceServer struct {
}

func (UnimplementedUserRoleServiceServer) UserRoleList(context.Context, *UserRoleListReq) (*UserRoleListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRoleList not implemented")
}
func (UnimplementedUserRoleServiceServer) UserRoleUpdate(context.Context, *UserRoleUpdateReq) (*UserRoleUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRoleUpdate not implemented")
}
func (UnimplementedUserRoleServiceServer) UserRoleInfo(context.Context, *UserRoleInfoReq) (*UserRoleInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRoleInfo not implemented")
}
func (UnimplementedUserRoleServiceServer) UserRoleAdd(context.Context, *UserRoleAddReq) (*UserRoleAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRoleAdd not implemented")
}
func (UnimplementedUserRoleServiceServer) UserRoleDelete(context.Context, *UserRoleDeleteReq) (*UserRoleDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRoleDelete not implemented")
}
func (UnimplementedUserRoleServiceServer) mustEmbedUnimplementedUserRoleServiceServer() {}

// UnsafeUserRoleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRoleServiceServer will
// result in compilation errors.
type UnsafeUserRoleServiceServer interface {
	mustEmbedUnimplementedUserRoleServiceServer()
}

func RegisterUserRoleServiceServer(s grpc.ServiceRegistrar, srv UserRoleServiceServer) {
	s.RegisterService(&UserRoleService_ServiceDesc, srv)
}

func _UserRoleService_UserRoleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRoleListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServiceServer).UserRoleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleService_UserRoleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServiceServer).UserRoleList(ctx, req.(*UserRoleListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleService_UserRoleUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRoleUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServiceServer).UserRoleUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleService_UserRoleUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServiceServer).UserRoleUpdate(ctx, req.(*UserRoleUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleService_UserRoleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRoleInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServiceServer).UserRoleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleService_UserRoleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServiceServer).UserRoleInfo(ctx, req.(*UserRoleInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleService_UserRoleAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRoleAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServiceServer).UserRoleAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleService_UserRoleAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServiceServer).UserRoleAdd(ctx, req.(*UserRoleAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserRoleService_UserRoleDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRoleDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRoleServiceServer).UserRoleDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRoleService_UserRoleDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRoleServiceServer).UserRoleDelete(ctx, req.(*UserRoleDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRoleService_ServiceDesc is the grpc.ServiceDesc for UserRoleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRoleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserRoleService",
	HandlerType: (*UserRoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserRoleList",
			Handler:    _UserRoleService_UserRoleList_Handler,
		},
		{
			MethodName: "UserRoleUpdate",
			Handler:    _UserRoleService_UserRoleUpdate_Handler,
		},
		{
			MethodName: "UserRoleInfo",
			Handler:    _UserRoleService_UserRoleInfo_Handler,
		},
		{
			MethodName: "UserRoleAdd",
			Handler:    _UserRoleService_UserRoleAdd_Handler,
		},
		{
			MethodName: "UserRoleDelete",
			Handler:    _UserRoleService_UserRoleDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

const (
	UserClassService_UserClassList_FullMethodName   = "/user.UserClassService/UserClassList"
	UserClassService_UserClassUpdate_FullMethodName = "/user.UserClassService/UserClassUpdate"
	UserClassService_UserClassInfo_FullMethodName   = "/user.UserClassService/UserClassInfo"
	UserClassService_UserClassAdd_FullMethodName    = "/user.UserClassService/UserClassAdd"
	UserClassService_UserClassDelete_FullMethodName = "/user.UserClassService/UserClassDelete"
)

// UserClassServiceClient is the client API for UserClassService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClassServiceClient interface {
	UserClassList(ctx context.Context, in *UserClassListReq, opts ...grpc.CallOption) (*UserClassListResp, error)
	UserClassUpdate(ctx context.Context, in *UserClassUpdateReq, opts ...grpc.CallOption) (*UserClassUpdateResp, error)
	UserClassInfo(ctx context.Context, in *UserClassInfoReq, opts ...grpc.CallOption) (*UserClassInfoResp, error)
	UserClassAdd(ctx context.Context, in *UserClassAddReq, opts ...grpc.CallOption) (*UserClassAddResp, error)
	UserClassDelete(ctx context.Context, in *UserClassDeleteReq, opts ...grpc.CallOption) (*UserClassDeleteResp, error)
}

type userClassServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClassServiceClient(cc grpc.ClientConnInterface) UserClassServiceClient {
	return &userClassServiceClient{cc}
}

func (c *userClassServiceClient) UserClassList(ctx context.Context, in *UserClassListReq, opts ...grpc.CallOption) (*UserClassListResp, error) {
	out := new(UserClassListResp)
	err := c.cc.Invoke(ctx, UserClassService_UserClassList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClassServiceClient) UserClassUpdate(ctx context.Context, in *UserClassUpdateReq, opts ...grpc.CallOption) (*UserClassUpdateResp, error) {
	out := new(UserClassUpdateResp)
	err := c.cc.Invoke(ctx, UserClassService_UserClassUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClassServiceClient) UserClassInfo(ctx context.Context, in *UserClassInfoReq, opts ...grpc.CallOption) (*UserClassInfoResp, error) {
	out := new(UserClassInfoResp)
	err := c.cc.Invoke(ctx, UserClassService_UserClassInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClassServiceClient) UserClassAdd(ctx context.Context, in *UserClassAddReq, opts ...grpc.CallOption) (*UserClassAddResp, error) {
	out := new(UserClassAddResp)
	err := c.cc.Invoke(ctx, UserClassService_UserClassAdd_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClassServiceClient) UserClassDelete(ctx context.Context, in *UserClassDeleteReq, opts ...grpc.CallOption) (*UserClassDeleteResp, error) {
	out := new(UserClassDeleteResp)
	err := c.cc.Invoke(ctx, UserClassService_UserClassDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserClassServiceServer is the server API for UserClassService service.
// All implementations must embed UnimplementedUserClassServiceServer
// for forward compatibility
type UserClassServiceServer interface {
	UserClassList(context.Context, *UserClassListReq) (*UserClassListResp, error)
	UserClassUpdate(context.Context, *UserClassUpdateReq) (*UserClassUpdateResp, error)
	UserClassInfo(context.Context, *UserClassInfoReq) (*UserClassInfoResp, error)
	UserClassAdd(context.Context, *UserClassAddReq) (*UserClassAddResp, error)
	UserClassDelete(context.Context, *UserClassDeleteReq) (*UserClassDeleteResp, error)
	mustEmbedUnimplementedUserClassServiceServer()
}

// UnimplementedUserClassServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserClassServiceServer struct {
}

func (UnimplementedUserClassServiceServer) UserClassList(context.Context, *UserClassListReq) (*UserClassListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserClassList not implemented")
}
func (UnimplementedUserClassServiceServer) UserClassUpdate(context.Context, *UserClassUpdateReq) (*UserClassUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserClassUpdate not implemented")
}
func (UnimplementedUserClassServiceServer) UserClassInfo(context.Context, *UserClassInfoReq) (*UserClassInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserClassInfo not implemented")
}
func (UnimplementedUserClassServiceServer) UserClassAdd(context.Context, *UserClassAddReq) (*UserClassAddResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserClassAdd not implemented")
}
func (UnimplementedUserClassServiceServer) UserClassDelete(context.Context, *UserClassDeleteReq) (*UserClassDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserClassDelete not implemented")
}
func (UnimplementedUserClassServiceServer) mustEmbedUnimplementedUserClassServiceServer() {}

// UnsafeUserClassServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserClassServiceServer will
// result in compilation errors.
type UnsafeUserClassServiceServer interface {
	mustEmbedUnimplementedUserClassServiceServer()
}

func RegisterUserClassServiceServer(s grpc.ServiceRegistrar, srv UserClassServiceServer) {
	s.RegisterService(&UserClassService_ServiceDesc, srv)
}

func _UserClassService_UserClassList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserClassListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserClassServiceServer).UserClassList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserClassService_UserClassList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserClassServiceServer).UserClassList(ctx, req.(*UserClassListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserClassService_UserClassUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserClassUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserClassServiceServer).UserClassUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserClassService_UserClassUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserClassServiceServer).UserClassUpdate(ctx, req.(*UserClassUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserClassService_UserClassInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserClassInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserClassServiceServer).UserClassInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserClassService_UserClassInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserClassServiceServer).UserClassInfo(ctx, req.(*UserClassInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserClassService_UserClassAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserClassAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserClassServiceServer).UserClassAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserClassService_UserClassAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserClassServiceServer).UserClassAdd(ctx, req.(*UserClassAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserClassService_UserClassDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserClassDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserClassServiceServer).UserClassDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserClassService_UserClassDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserClassServiceServer).UserClassDelete(ctx, req.(*UserClassDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserClassService_ServiceDesc is the grpc.ServiceDesc for UserClassService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserClassService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserClassService",
	HandlerType: (*UserClassServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserClassList",
			Handler:    _UserClassService_UserClassList_Handler,
		},
		{
			MethodName: "UserClassUpdate",
			Handler:    _UserClassService_UserClassUpdate_Handler,
		},
		{
			MethodName: "UserClassInfo",
			Handler:    _UserClassService_UserClassInfo_Handler,
		},
		{
			MethodName: "UserClassAdd",
			Handler:    _UserClassService_UserClassAdd_Handler,
		},
		{
			MethodName: "UserClassDelete",
			Handler:    _UserClassService_UserClassDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
