// Code generated by goctl. DO NOT EDIT.
// Source: office.proto

package officeservice

import (
	"context"

	"example/app/company/cmd/rpc/office/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateOfficeRequest  = pb.CreateOfficeRequest
	CreateOfficeResponse = pb.CreateOfficeResponse
	DeleteOfficeRequest  = pb.DeleteOfficeRequest
	DeleteOfficeResponse = pb.DeleteOfficeResponse
	GetOfficeRequest     = pb.GetOfficeRequest
	GetOfficeResponse    = pb.GetOfficeResponse
	ListOfficeRequest    = pb.ListOfficeRequest
	ListOfficeResponse   = pb.ListOfficeResponse
	Office               = pb.Office
	UpdateOfficeRequest  = pb.UpdateOfficeRequest
	UpdateOfficeResponse = pb.UpdateOfficeResponse

	OfficeService interface {
		CreatOffice(ctx context.Context, in *CreateOfficeRequest, opts ...grpc.CallOption) (*CreateOfficeResponse, error)
		DeleteOffice(ctx context.Context, in *DeleteOfficeRequest, opts ...grpc.CallOption) (*DeleteOfficeResponse, error)
		UpdateOffice(ctx context.Context, in *UpdateOfficeRequest, opts ...grpc.CallOption) (*UpdateOfficeResponse, error)
		GetOffice(ctx context.Context, in *GetOfficeRequest, opts ...grpc.CallOption) (*GetOfficeResponse, error)
		ListOffice(ctx context.Context, in *ListOfficeRequest, opts ...grpc.CallOption) (*ListOfficeResponse, error)
	}

	defaultOfficeService struct {
		cli zrpc.Client
	}
)

func NewOfficeService(cli zrpc.Client) OfficeService {
	return &defaultOfficeService{
		cli: cli,
	}
}

func (m *defaultOfficeService) CreatOffice(ctx context.Context, in *CreateOfficeRequest, opts ...grpc.CallOption) (*CreateOfficeResponse, error) {
	client := pb.NewOfficeServiceClient(m.cli.Conn())
	return client.CreatOffice(ctx, in, opts...)
}

func (m *defaultOfficeService) DeleteOffice(ctx context.Context, in *DeleteOfficeRequest, opts ...grpc.CallOption) (*DeleteOfficeResponse, error) {
	client := pb.NewOfficeServiceClient(m.cli.Conn())
	return client.DeleteOffice(ctx, in, opts...)
}

func (m *defaultOfficeService) UpdateOffice(ctx context.Context, in *UpdateOfficeRequest, opts ...grpc.CallOption) (*UpdateOfficeResponse, error) {
	client := pb.NewOfficeServiceClient(m.cli.Conn())
	return client.UpdateOffice(ctx, in, opts...)
}

func (m *defaultOfficeService) GetOffice(ctx context.Context, in *GetOfficeRequest, opts ...grpc.CallOption) (*GetOfficeResponse, error) {
	client := pb.NewOfficeServiceClient(m.cli.Conn())
	return client.GetOffice(ctx, in, opts...)
}

func (m *defaultOfficeService) ListOffice(ctx context.Context, in *ListOfficeRequest, opts ...grpc.CallOption) (*ListOfficeResponse, error) {
	client := pb.NewOfficeServiceClient(m.cli.Conn())
	return client.ListOffice(ctx, in, opts...)
}
