// Code generated by goctl. DO NOT EDIT.
package types

type Employee struct {
	Id       int64  `json:"id" tag:"员工id"`
	Name     string `json:"name" tag:"员工姓名"`
	Age      int64  `json:"age" tag:"员工年龄"`
	Company  string `json:"company" tag:"员工公司"`
	Phone    string `json:"phone" tag:"员工电话"`
	OfficeID int64  `json:"officeID" tag:"办公室id"`
}

type EmployeeCreateRequest struct {
	Name     string `json:"name" tag:"员工姓名"`
	Age      int64  `json:"age" tag:"员工年龄"`
	Company  string `json:"company" tag:"员工公司"`
	Phone    string `json:"phone" tag:"员工电话"`
	OfficeID int64  `json:"officeID" tag:"办公室id"`
}

type EmployeeCreateResponse struct {
	Msg string `json:"msg" tag:"返回信息"`
}

type EmployeeDeleteRequest struct {
	Id int64 `json:"id" tag:"员工id"`
}

type EmployeeDeleteResponse struct {
	Msg string `json:"msg" tag:"返回信息"`
}

type EmployeeUpdateRequest struct {
	Id       int64  `path:"id" tag:"员工id"`
	Name     string `json:"name,optional" tag:"员工姓名"`
	Age      int64  `json:"age,optional" tag:"员工年龄"`
	Company  string `json:"company,optional" tag:"员工公司"`
	Phone    string `json:"phone,optional" tag:"员工电话"`
	OfficeID int64  `json:"officeID,optional" tag:"办公室id"`
}

type EmployeeUpdateResponse struct {
	Msg string `json:"msg" tag:"返回信息"`
}

type EmployeeDetailRequest struct {
	Id int64 `form:"id" tag:"员工id"`
}

type EmployeeDetailResponse struct {
	Employee Employee `json:"employee" tag:"员工信息"`
}

type EmployeeListRequest struct {
	Page     int64  `form:"page" tag:"页码"`
	PageSize int64  `form:"pageSize" tag:"每页条数"`
	Search   string `form:"search,optional" tag:"搜索关键字,支持姓名,公司,地址"`
	Sort     string `form:"sort,optional" tag:"排序字段,默认按照id排序,可选值id,name,age,company,phone,officeID"`
	Order    string `form:"order,optional" tag:"排序方式, 默认为升序asc, 可选值: asc, desc"`
}

type EmployeeListResponse struct {
	Total int64      `json:"total" tag:"总条数"`
	List  []Employee `json:"list" tag:"员工列表"`
}

type Office struct {
	ID      int64  `json:"id" description:"办公室ID"`
	Name    string `json:"name" description:"办公室名称"`
	Address string `json:"address" description:"办公室地址"`
}

type OfficeCreateRequest struct {
	Name    string `json:"name" description:"办公室名称"`
	Address string `json:"address" description:"办公室地址"`
}

type OfficeCreateResponse struct {
	Msg string `json:"msg" tag:"返回信息"`
}

type OfficeDeleteRequest struct {
	ID int64 `json:"id" description:"办公室ID"`
}

type OfficeDeleteResponse struct {
	Msg string `json:"msg" tag:"返回信息"`
}

type OfficeUpdateRequest struct {
	ID      int64  `path:"id" description:"办公室ID"`
	Name    string `json:"name,optional" description:"办公室名称"`
	Address string `json:"address,optional" description:"办公室地址"`
}

type OfficeUpdateResponse struct {
	Msg string `json:"msg" tag:"返回信息"`
}

type OfficeDetailRequest struct {
	ID int64 `form:"id" description:"办公室ID"`
}

type OfficeDetailResponse struct {
	Office Office `json:"office" description:"办公室信息"`
}

type OfficeListRequest struct {
	Page     int    `form:"page" description:"页码"`
	PageSize int    `form:"pageSize" description:"每页条数"`
	Search   string `form:"search,optional" description:"搜索关键字, 支持办公室名称或地址"`
	Sort     string `form:"sort,optional" description:"排序字段, 默认按照ID排序, 可选值: id, name, address"`
	Order    string `form:"order,optional" description:"排序方式, 默认为升序asc, 可选值: asc, desc"`
}

type OfficeListResponse struct {
	Total int      `json:"total" description:"总条数"`
	List  []Office `json:"list" description:"办公室列表"`
}
